version: "3.8"

services:
  database_library:
    image: postgres
    container_name: database_library
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=library
    volumes:
      - pgdata:/data/postgres
    network_mode: "host"
  app:
    build: .
    container_name: backend
    volumes:
      - .:/usr/app
    network_mode: "host"

volumes:
  pgdata:
    driver: local